### ISSUE TITLE
三个界面的图标大小不一致

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-web#100]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Mac mini Os X EI Capitan
Version: 10.11.6

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.98 (64-bit)

**What I want to do**
想看三个界面的所有图标

**Where I am**
任意一个界面

**What I have done**
进入任意一个界面，看每个界面里的图标

**What I expect:**
三个界面里app和service的图标大小一致

**What really happened**:
三个界面里的图标大小不统一

**Comment by dorry-terryli** [comment]
会修改图标大小
