### ISSUE TITLE
app start失败提示不全

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#104]
**Dorry UI Build Versin:**
Version:  0.1.12-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
start app

**Where I am**
app页面

**What I have done**
点击start按钮

**What I expect:**
启动成功

**What really happened**:
启动失败，弹出一个提示"ERROR"。没有指明start失败还是remove失败，也没用app名称和失败的原因。

**Comment by BelindaLiu** [comment]
![screenshot from 2017-01-06 15-15-27](https://cloud.githubusercontent.com/assets/10137744/21710801/edf33494-d425-11e6-8e7f-d4dd1b7656a8.png)

**Comment by dorry-terryli** [comment]
arm docker 版本为 1.11.2 　x86 docker 版本为1.12.1
根据[https://github.com/docker/docker/blob/master/CHANGELOG.md](changelog) 
1.12.0 (2016-07-28) error message 包含在json object中，次版本之前都是string．
现已支持两种格式

**Comment by dorrywhale** [comment]
@dorry-terryli 请提供一个启动会失败的场景，目前测试中没找到。

**Comment by dorry-terryli** [comment]
@dorrywhale alpine cmd 为空，启动错误

**Comment by dorrywhale** [comment]
OK, pass scenario
