### ISSUE TITLE
[UI]test1-mouseover 'remove all'

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-web#11]
**System:**
Mac mini Os X EI Capitan

**Browser:**
Chrome 

**What I want to do**
I want to see the feedback when mouseover 'remove all' buttion.

**Where I am**
services page

**What I have done**
I mouseover 'remove all' button and see its feedback.

**What I expect:**
The word 'remove all' will display underline when mouseover it.
![ee306455-cf52-4461-a690-8e106e7d95c1](https://cloud.githubusercontent.com/assets/22925114/19545974/deedf9c0-96bd-11e6-82d7-64ef5191c4de.png)

**What really happened**
When i mouseover 'remove all' button,the button has no feedback.
![the icon and text-bug](https://cloud.githubusercontent.com/assets/22925114/19547511/22ff4904-96cb-11e6-98f9-111e58438970.png)

**Comment by Anna-92** [comment]
一般状态下，remove all和icon的不透明度是71%
鼠标悬停时，remove all和icon的不透明度是100%
点击时，remove all下方出现下划线

**Comment by dorry-terryli** [comment]
Remove the fixed tag.We will reconsider the problem. @Anna-92

**Comment by Anna-92** [comment]
‘Oops! There Is Something Wrong’，垃圾箱Icon和remove all的中心在一条线上 @dorry-terryli

**Comment by LiuBiHongHong** [comment]
fixed @Anna-92
