### ISSUE TITLE
login页面没有反应

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#110]
**Dorry UI Build Versin:**
Version:  0.1.1４-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
登录

**Where I am**
login页面

**What I have done**
填写账号信息，然后点击登录

**What I expect:**
登录成功

**What really happened**:
登录中、成功、失败的提示都没有。
![screenshot from 2017-01-06 15-10-23](https://cloud.githubusercontent.com/assets/10137744/21711003/388f77b4-d427-11e6-8872-e3607da8fae1.png)

**Comment by dorry-terryli** [comment]
登录失败提示"Incorrect username or password."，登录成功直接转跳page

**Comment by dorrywhale** [comment]
pass scenario in v0.1.15, which is written as v 0.1.12 by mistake.
