### ISSUE TITLE
login页面联系方式有误

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#113]
**Dorry UI Build Versin:**
Version:  0.1.1４-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**

**Where I am**
login页面

**What I have done**
查看联系方式

**What I expect:**
看到正确的联系方式，如邮箱。

**What really happened**:
110

**Comment by BelindaLiu** [comment]
![screenshot from 2017-01-06 15-58-23](https://cloud.githubusercontent.com/assets/10137744/21711358/7dace03c-d429-11e6-985e-813e0a577ed3.png)

**Comment by dorrywhale** [comment]
support@dorry.io

**Comment by dorry-terryli** [comment]
修改为　support@dorry.io mailto link

**Comment by dorrywhale** [comment]
pass scenario in v0.1.12
