### ISSUE TITLE
service页面里没有用户名

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-web#116]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Mac mini Os X EI Capitan
Version: 10.11.6

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.98 (64-bit)

**What I want to do**
我想看到工具栏上的用户名和sign out

**Where I am**
service页面

**What I have done**
进入service页面查看工具栏上的用户名和sing out

**What I expect:**
在工具栏上看到用户名和sign out

**What really happened**:
1、只有sign out,没有相应的图标
2、用户名没有显示

**Comment by dorry-terryli** [comment]
@Anna-92　现显示用户名及signout
