### ISSUE TITLE
stopped service里的app name写成了application

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-web#118]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Mac mini Os X EI Capitan
Version: 10.11.6

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.98 (64-bit)

**What I want to do**
想stop 一个service

**Where I am**
service页面

**What I have done**
stop了一个service

**What I expect:**
stopped service里的信息是正确的

**What really happened**:
running service里的app name在stopped service列表里写成了application

![6675a9db-3d53-4910-9d9f-92de53f69e21](https://cloud.githubusercontent.com/assets/22925114/21713479/2472dd62-d435-11e6-891a-b59502d95725.png)

**Comment by dorrywhale** [comment]
v0.1.12 scenario 过了

**Comment by dorry-terryli** [comment]
My mistake , scenario verion should be v0.1.15. I will fix it.
