### ISSUE TITLE
[UI]test1-mouseover 'restart' button and 'stop' button

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-web#13]
**System:**
Mac mini Os X EI Capitan

**Browser:**
Chrome 

**What I want to do**
I want to see the feedback when i mouseover 'restert' button, 'stop' button or 'remove' button.

**Where I am**
services page

**What I have done**
I mouseovered 'restart' button, ' stop' button or 'remove' button and see their feedback.

**What I expect:**
I can see the state when mouseovering the buttons.

**What really happened**:
I couldn't get the feedback when I mouseovering one button.

**Comment by dorry-terryli** [comment]
@Anna-92 The problem is fixed.Please confirm it.
