### ISSUE TITLE
[UI] test1-stop one service

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-web#2]
**System:**
Mac mini Os X EI Capitan

**Browser:**
Chrome 

**What I want to do**
I want to stop one service.

**Where I am**
service page

**What I have done**
I clicked the 'stop' button of one of the running services.

**What I expect:**
The stopped service can be displayed in 'stopped services' quickly.

**What really happened**
I had to reload the page manually to see the result, and the speed of reloading is low.

**Comment by Anna-92** [comment]
一个被stopped的应用应显示于stopped services里的第一个位置 @dorry-terryli

**Comment by BelindaLiu** [comment]
stop service是危险操作，希望提示确认停止某个service。

**Comment by LiuBiHongHong** [comment]
@Anna-92 fixed
