### ISSUE TITLE
[UI]test1-点击'start new'按钮启动一个APP的服务

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-web#20]
**System:**
Mac mini Os X EI Capitan

**Browser:**
Chrome 

**What I want to do**
我想点击一个APP的’start new'按钮启动它的service.

**Where I am**
App page

**What I have done**
我点击了任何一个APP的‘start new’按钮试图启动一个app的服务.

**What I expect:**
我希望当我点击它时，我能看到按钮上的文字变成一个进度条，表示启动服务中的状态.

**What really happened**:
我点击'start new'按钮时，它毫无反应.

**Comment by Anna-92** [comment]
当我点击了一个 'start new’ button后，我看不到它的启动过程。

**Comment by BelindaLiu** [comment]
start成功以后希望看到生成的service名称，不然很难找到。

**Comment by LiuBiHongHong** [comment]
@Anna-92
