### ISSUE TITLE
[UI]test1-wrong service里‘remove all'与Icon不对齐

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-web#29]
**System:**
Mac mini Os X EI Capitan

**Browser:**
Chrome 

**What I want to do**
我希望看到remove all与垃圾箱icon以及‘Oops!There is Something wrong'的中心在一条线上.

**Where I am**
Service page

**What I have done**
我检查了remove all与垃圾箱icon是否居中.

**What I expect:**
我希望remove all和垃圾箱icon的中心是在一条线上的 .

**What really happened**:
remove all与垃圾箱Icon明细位置错开来了.

**Comment by LiuBiHongHong** [comment]
@Anna-92 
Try to use cdn

**Comment by LiuBiHongHong** [comment]
@Anna-92 fixed
