### ISSUE TITLE
第一次部署，默认页不显示任何有效内容

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#34]
**Dorry UI Build Versin:**
Version: 0.1.2-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
 我部署完dorryos以后，想要到管理中心查看dorryos里有哪些东西。

**Where I am**
到默认页

**What I have done**
查看页面

**What I expect:**
希望看到内容统计，或者标题介绍，或者使用方法的提示和说明。

**What really happened**:
只有一个刷新按钮，除了浏览器地址写着service，没有其它任何说明，来解释现在这个页面是什么页面，以及dorryos是什么状态，或者
![screenshot from 2016-10-28 11-46-39](https://cloud.githubusercontent.com/assets/10137744/19797616/dbd9697e-9d1e-11e6-80b0-d7dcb8ef96cf.png)
我应该做什么操作。

**Comment by Anna-92** [comment]
我会设计一个操作说明，提示用户要首先去Market下载应用，在app里面启动服务，才能在service里看到已启动的服务。
