### ISSUE TITLE
app为空时，页面一片空白

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#35]
**Dorry UI Build Versin:**
Version: 0.1.2-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
我想查看当前app的统计状态

**Where I am**
app页面

**What I have done**
点击左侧方块形按钮

**What I expect:**
看到统计的app个数为０，或者一条提示告诉我这个方块指向的页面是什么，为什么一片空白

**What really happened**:
页面什么都没有
![screenshot from 2016-10-28 11-54-31](https://cloud.githubusercontent.com/assets/10137744/19797831/1432d804-9d20-11e6-80c3-1bc8a84ea041.png)

**Comment by Anna-92** [comment]
我考虑设计一个提示框,里面写‘There is no app in this app'。
