### ISSUE TITLE
footer没有分隔符

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#38]
![Uploading Screenshot from 2016-10-28 11-40-18.png…]()
**Dorry UI Build Versin:**
Version: 0.1.2-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想查看dorryos版本信息

**Where I am**
任意页面

**What I have done**
查看footer

**What I expect:**
看到版本信息

**What really happened**:
版本信息有两个，但是没有明显断句或者分割
![screenshot from 2016-10-28 11-37-44](https://cloud.githubusercontent.com/assets/10137744/19798305/b6adf2d8-9d22-11e6-9848-46ae472b8d48.png)

**Comment by Anna-92** [comment]
@dorry-terryli 两个版本信息之间距离再增加一倍，

**Comment by Anna-92** [comment]
@dorry-terryli 设计稿如下：
![footer](https://cloud.githubusercontent.com/assets/22925114/19853863/d35c261c-9fa6-11e6-87e1-3e35d74717a1.png)

数据：
copyright:#9C9C9C  typeface:arial
Docker API Version 和 UI Version  size:13px  regular
1.22 or v0.1.2-alpha size:14px blod

**Comment by dorry-terryli** [comment]
@Anna-92 fixed this problem
