### ISSUE TITLE
页面信息显示不全，都是“...”

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#39]
![Uploading Screenshot from 2016-10-28 11-40-18.png…]()
**Dorry UI Build Versin:**
Version: 0.1.2-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想查看service或者app

**Where I am**
service或app页面

**What I have done**
查看详情或者当前页

**What I expect:**
看到准确信息

**What really happened**:
甚至详情的标题都是"..."，而且hover上去也不会显示全称。
并且exited(137)3...，后面的时间根本看不到。
![screenshot from 2016-10-28 11-34-38](https://cloud.githubusercontent.com/assets/10137744/19798364/36d2d37a-9d23-11e6-85c4-0cbe05fc58af.png)

**Comment by Anna-92** [comment]
@dorry-terryli 
app详情页里的名字应当显示全名，若名字较长，则超出部分写道第二行里。
service里的；exited91247...后面省略隐藏的部分全部显示出来。

**Comment by LiuBiHongHong** [comment]
@BelindaLiu fixed

**Comment by BelindaLiu** [comment]
v0.1.8-alpha app 页面已修复。

**Comment by dorrywhale** [comment]
@LiuBiHongHong 请修复

**Comment by BelindaLiu** [comment]
V0.1.12-alpha fixed.
