### ISSUE TITLE
[UI] test1-see the user head

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-web#4]
**System:**
Mac mini Os X EI Capitan

**Browser:**
Chrome 

**What I want to do**
I want to see the user head and name.

**Where I am**
services page

**What I have done**
I click 'services' button in menu and see the page of services.

**What I expect:**
I can see user head and name at the top right-hand corner. 
![user head](https://cloud.githubusercontent.com/assets/22925114/19512797/29f1023a-9620-11e6-8abd-f0a89e114939.png)

**What really happened**
![user head and name](https://cloud.githubusercontent.com/assets/22925114/19512485/b37534ce-961e-11e6-909f-e818b7aa6d80.png)

**Comment by dorry-terryli** [comment]
@Anna-92 Fix the problem.Please confirm
