### ISSUE TITLE
service名称等信息混乱

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#40]
**Dorry UI Build Versin:**
Version: 0.1.2-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想要查看新生成的service

**Where I am**
service页面

**What I have done**
先在app页面start

**What I expect:**
app对应的新生成的service出现

**What really happened**:
service名称拟人化，无法看出是哪个app生成的，也没有详细信息。

**Comment by BelindaLiu** [comment]
![screenshot from 2016-10-28 11-32-43](https://cloud.githubusercontent.com/assets/10137744/19798457/c577559c-9d23-11e6-96a1-ba50760ead58.png)
![screenshot from 2016-10-28 11-32-43](https://cloud.githubusercontent.com/assets/10137744/19798556/5fc225e6-9d24-11e6-8ada-9fcd6f54a678.png)

**Comment by Anna-92** [comment]
@dorry-terryli 请问可以通过技术在service的名字中体现出app的名字吗？如果技术实现有问题或者因此导致service过长，我会考虑给出新的设计，在service的信息中，加上app的名字。

**Comment by dorry-terryli** [comment]
可以，但是直接接在service name中会出现过长的现象，建议重新设计界面

**Comment by Anna-92** [comment]
@dorry-terryli 
标注好的label.png已上传至smb上service文件夹里的子文件夹measurement里。整体布局参数不变，只需调整wrong service,stopped service和running service的间距，以及在service名字下方增加app名字。ps:字符15个，超过一律省略号显示。颜色与days,port的一致。

**Comment by LiuBiHongHong** [comment]
@BelindaLiu fixed

**Comment by BelindaLiu** [comment]
只有running service显示了。

**Comment by BelindaLiu** [comment]
Version: 0.2.0-hotfix-alpha fixed
