### ISSUE TITLE
stopped service 与 something wrong内容完全一致

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#42]
![Uploading Screenshot from 2016-10-28 11-40-18.png…]()
**Dorry UI Build Versin:**
Version: 0.1.2-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想查看service

**Where I am**
service页面

**What I have done**
查看当前页

**What I expect:**
看到准确信息

**What really happened**:
不管是手动stop一个service，还是start以后自动停止运行的service都会出现在两栏中，remove或者restart以后，两栏同时产生变化。
tips,有些是exit(1)，有的是exit(137)。

**Comment by LiuBiHongHong** [comment]
@BelindaLiu fixed

**Comment by BelindaLiu** [comment]
v0.1.8-alpha fixed.
