### ISSUE TITLE
无法启动chinadns

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#43]
**Dorry UI Build Versin:**
Version: 0.1.2-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想启动一个chinadns服务

**Where I am**
app页面

**What I have done**
点击start，页面出现container started。

**What I expect:**
增加一个running service

**What really happened**:
running service里出现一条，1秒内出现在stop 和something wrong中。

**Comment by Anna-92** [comment]
@dorry-terryli 请你们检查这个bug是什么情况后告诉我

**Comment by dorry-terryli** [comment]
@Anna-92 app点击start new启动，显示container started提示，service启动过程中出现错误，停止启动，service处于stop状态，然后出现在stop框中

**Comment by BelindaLiu** [comment]
v0.1.6-alpha fixed.
