### ISSUE TITLE
start 多个aiphine 3:2后，无法找到service

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#44]
**Dorry UI Build Versin:**
Version: 0.1.2-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想启动多个alphine服务

**Where I am**
app页面

**What I have done**
点击start，大概６次

**What I expect:**
增加６个running service

**What really happened**:
app页面显示container created，service 页面没有任何变化，10分钟内无任何改变。
１个小时内，增加了2个stopped的container，但是没有有效信息，无法确认是什么app。

**Comment by Anna-92** [comment]
@LiuBiHongHong 在App 页面中， service启动成功的提示是错误的。请重现问题，告知我情况，我考虑设计出错交互。

**Comment by BelindaLiu** [comment]
v0.1.6-alpha fixed.
