### ISSUE TITLE
restart一些service根本没有效果

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#46]
**Dorry UI Build Versin:**
Version: 0.1.2-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想restart一个chinadns服务

**Where I am**
service页面

**What I have done**
点击restart

**What I expect:**
增加一个running service

**What really happened**:
service1秒内又回到鼠标底下。并且无任何提示。

**Comment by Anna-92** [comment]
我会设计restart的提示信息， 包括成功和失败的。

**Comment by dorry-terryli** [comment]
@Anna-92 已添加service start restart stop 提示信息
