### ISSUE TITLE
app删除过程中没有任何提示

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#49]
**Dorry UI Build Versin:**
Version: 0.1.2-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想删除app

**Where I am**
app页面

**What I have done**
删除几个app

**What I expect:**
看到正在删除或者删除成功的提示

**What really happened**:
页面没有任何变化，可以一直重新点击删除，也没有任何标记提醒这个app正在删除中。

**Comment by LiuBiHongHong** [comment]
@BelindaLiu fixed

**Comment by BelindaLiu** [comment]
v0.1.8-alpha fixed.
