### ISSUE TITLE
[UI] test1-see the copyright

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-web#5]
**System:**
Mac mini Os X EI Capitan

**Browser:**
Chrome 

**What I want to do**
I want to see the copyright about DorryOS.

**Where I am**
services page

**What I have done**
I saw the copyright at the lower right.

**What I expect:**
I can see copyright at the lower right. 
![copyright](https://cloud.githubusercontent.com/assets/22925114/19512726/e494f80e-961f-11e6-8fb9-628dc2c54c7d.png)

**What really happened**
![copyright](https://cloud.githubusercontent.com/assets/22925114/19512676/97afe9b8-961f-11e6-886b-b6f4e041aee6.png)

**Comment by Anna-92** [comment]
PS:我希望底部写有版本号的区域固定不动，若页面内容多，需要滚动浏览，希望内容显示的区域在工具栏和版本栏之间。

**Comment by LiuBiHongHong** [comment]
@Anna-92 fixed
