### ISSUE TITLE
stop service没有提示

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#50]
**Dorry UI Build Versin:**
Version: 0.1.2-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想stop service

**Where I am**
service页面

**What I have done**
stop 1个 service

**What I expect:**
stop service是危险操作，希望提示是哪一个service，并且可以取消这个操作。
确认stop以后，希望当前service显示stop中，而不是可以继续点击stop。

**What really happened**:
几秒内页面没有任何变化，之后弹出一个stop成功的提示，但是也没有说明是哪个service。

**Comment by Anna-92** [comment]
@dorry-terryli 我会设计两个显示service被操作后状态的变更以及显示它处于正在操作中状态的高保真设计稿。

**Comment by BelindaLiu** [comment]
v0.1.6-alpha，stop service 已经有了确认弹窗，但是没有stopping状态。

**Comment by LiuBiHongHong** [comment]
@BelindaLiu fixed

**Comment by BelindaLiu** [comment]
v0.1.8-alpha fixed.
