### ISSUE TITLE
market页面一片空白

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#55]
**Dorry UI Build Versin:**
Version: 0.1.6-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想看market页面有什么内容

**Where I am**
market页面

**What I have done**
点击左侧按钮

**What I expect:**
显示介绍并且有功能可以使用

**What really happened**:
一片空白
![screenshot from 2016-11-10 09-41-53](https://cloud.githubusercontent.com/assets/10137744/20161658/c354add0-a72a-11e6-96da-ca17991108c5.png)

**Comment by dorry-terryli** [comment]
added tips,show it after next build @BelindaLiu
