### ISSUE TITLE
没有确定删除app，但app图标上出现旋转的圆圈

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#56]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想delete app

**Where I am**
app页面

**What I have done**
delete 1个 app

**What I expect:**
显示确认页面

**What really happened**:
弹出弹窗的同时，app上出现一个旋转的圆圈。
![screenshot from 2016-11-10 09-44-05](https://cloud.githubusercontent.com/assets/10137744/20161855/2d2bf8e8-a72c-11e6-857d-48dd27d281d3.png)

**Comment by LiuBiHongHong** [comment]
@BelindaLiu fixed

**Comment by BelindaLiu** [comment]
v0.1.8-alpha fixed.
