### ISSUE TITLE
删除app的失败提示不明确易懂

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#57]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想delete app

**Where I am**
app页面

**What I have done**
delete 1个 app

**What I expect:**
显示delete成功

**What really happened**:
弹出一个黄色的提示，没有明确的说明是什么操作，以及操作结果到底是成功还是失败。
![screenshot from 2016-11-10 10-01-18](https://cloud.githubusercontent.com/assets/10137744/20162013/195d97da-a72d-11e6-835b-ad210874a497.png)

**Comment by LiuBiHongHong** [comment]
@BelindaLiu fixed

**Comment by BelindaLiu** [comment]
现在是unsuccessfully, 能不能改成 failed? @Anna-92

**Comment by Anna-92** [comment]
可以 @BelindaLiu @dorry-terryli

**Comment by BelindaLiu** [comment]
Version: 0.2.0-hotfix-alpha fixed
