### ISSUE TITLE
app页面提示框太大

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#58]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想启动app

**Where I am**
app页面

**What I have done**
点击start new按钮

**What I expect:**
显示启动成功

**What really happened**:
弹出一个跟app模块等宽，跟确认删除弹窗差不多长的大模块，显示启动失败。
这个提示的位置、大小和确认弹窗差不多，感觉像是触发了某个新的功能模块。
这个提示完全遮住了两个app模块，影响用户操作这两个模块。
![screenshot from 2016-11-10 10-05-45](https://cloud.githubusercontent.com/assets/10137744/20162398/c0519bde-a72f-11e6-893e-b97cd5cb47b8.png)

**Comment by Anna-92** [comment]
我会调整弹出框模块的尺寸。

**Comment by Anna-92** [comment]
我会考虑重新设计弹出框的尺寸

**Comment by BelindaLiu** [comment]
Version: 0.2.0-hotfix-alpha fixed
