### ISSUE TITLE
点击一个app的start new按钮会影响到其它app的start new按钮

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#59]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想启动app

**Where I am**
app页面

**What I have done**
点击start new按钮

**What I expect:**
显示启动成功

**What really happened**:
当前app的start new按钮从绿色回到灰色，但是其它所有的start new按钮同时抖动了一下。
并且start过程中，当前按钮为starting状态，其它所有按钮消失。
![screenshot from 2016-11-10 10-27-13](https://cloud.githubusercontent.com/assets/10137744/20162784/3dda6598-a732-11e6-81de-3d0b9a1aefd1.png)

**Comment by dorry-terryli** [comment]
@BelindaLiu

**Comment by LiuBiHongHong** [comment]
@BelindaLiu fixed

**Comment by BelindaLiu** [comment]
v0.1.8-alpha fixed
