### ISSUE TITLE
文字超出了app的确认删除页面

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#60]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想delete app

**Where I am**
app页面

**What I have done**
delete 1个 app

**What I expect:**
显示delete成功

**What really happened**:
弹出一个确认是否删除的页面，里面的文字超出了删除弹窗的范围。
![screenshot from 2016-11-10 10-57-26](https://cloud.githubusercontent.com/assets/10137744/20163092/b3e98708-a734-11e6-98cb-d9d288a8b9ce.png)

**Comment by Anna-92** [comment]
我会重新设计文字显示

**Comment by BelindaLiu** [comment]
v0.1.8-alpha fixed.
