### ISSUE TITLE
service页面remove all确认弹窗的提示不正确

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#61]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想删除所有出错的service

**Where I am**
service页面

**What I have done**
点击remove all按钮

**What I expect:**
显示成功

**What really happened**:
弹出一个确认窗。提示是否删除所有service，但其实是删除了所有出错的service，并不包含running service。
![screenshot from 2016-11-10 11-06-53](https://cloud.githubusercontent.com/assets/10137744/20163289/4302d9ca-a736-11e6-99cf-4b6f5d0b3923.png)

**Comment by LiuBiHongHong** [comment]
@BelindaLiu fixed

**Comment by BelindaLiu** [comment]
v0.1.8-alpha fixed.
