### ISSUE TITLE
启动app的失败提示不明确易懂

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#62]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想启动app

**Where I am**
app页面

**What I have done**
点击start new按钮

**What I expect:**
显示启动成功

**What really happened**:
弹出一个黄色的提示，没有明确的说明是删除操作还是启动操作，只是说has server error。
![screenshot from 2016-11-10 11-12-56](https://cloud.githubusercontent.com/assets/10137744/20163385/18f2f04c-a737-11e6-9ca1-b8e392c2d102.png)

**Comment by LiuBiHongHong** [comment]
@BelindaLiu fixed

**Comment by BelindaLiu** [comment]
v0.1.8-alpha fixed.
