### ISSUE TITLE
app页面显示一个无法操作的dorry web

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#63]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想启动名叫dorry web的app　

**Where I am**
app页面

**What I have done**
点击start new按钮

**What I expect:**
显示启动成功

**What really happened**:
启动失败，而且删除也失败。
![screenshot from 2016-11-10 11-27-21](https://cloud.githubusercontent.com/assets/10137744/20163641/1542bd40-a739-11e6-940d-196955abc23f.png)

**Comment by dorry-terryli** [comment]
fixed @BelindaLiu

**Comment by BelindaLiu** [comment]
v0.1.8-alpha fixed.
