### ISSUE TITLE
app信息没有单独显示版本号

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#68]
**Dorry UI Build Versin:**
Version:  0.2.0-hotfix-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想查看app信息

**Where I am**
app页面

**What I have done**
查看app信息

**What I expect:**
单独显示版本号，如：
dorry-web
version: 0.1.0

**What really happened**:
只有dorryweb:0.1.0
![screenshot from 2016-12-09 11-14-59](https://cloud.githubusercontent.com/assets/10137744/21036528/629a6d70-be01-11e6-9d5d-5cc924b5c7b4.png)

**Comment by BelindaLiu** [comment]
"版本号"应该是`Version`,　而不是｀Tag｀.

**Comment by dorrywhale** [comment]
Pass scenario
