### ISSUE TITLE
app确认删除的弹窗中警示信息不全

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#71]
**Dorry UI Build Versin:**
Version:  0.2.0-hotfix-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想删除app

**Where I am**
app页面

**What I have done**
点击remove按钮

**What I expect:**
确认弹窗中警告可能有服务正在使用这个app

**What really happened**:
只是提示了app名称

**Comment by dorrywhale** [comment]
描述改为：
**Name:Version** may not be removed since its services are running. Do you want to remove it ?

**Comment by dorry-terryli** [comment]
描述按照 @dorrywhale 提供的修改

**Comment by dorrywhale** [comment]
Pass scenario
