### ISSUE TITLE
sidebar 页面不应该出现docker api version

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#74]
**Dorry UI Build Versin:**
Version:  0.2.0-hotfix-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想查看版本信息

**Where I am**
任意页面

**What I have done**
查看menubar的footer

**What I expect:**
version

**What really happened**:
除了version，还有一个docker api version

**Comment by dorrywhale** [comment]
Scenario 通过

**Comment by BelindaLiu** [comment]
V0.1.12-alpha fixed
