### ISSUE TITLE
service状态不明确

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#75]
**Dorry UI Build Versin:**
Version:  0.2.0-hotfix-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想查看service信息

**Where I am**
service页面

**What I have done**
查看页面

**What I expect:**
不同状态区块之间有明显的分割
明确的状态描述

**What really happened**:
不同状态的区块之间没有明显的区分，和叫oops的状态。

**Comment by Anna-92** [comment]
开发需要将图标的默认图片更换，并区分不同状态的图片颜色，我这边看效果后再考虑给出新设计。

**Comment by BelindaLiu** [comment]
V0.1.12-alpha fixed.
