### ISSUE TITLE
出错的service不应该显示端口

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#76]
**Dorry UI Build Versin:**
Version:  0.2.0-hotfix-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想查看service信息

**Where I am**
service页面

**What I have done**
查看

**What I expect:**
出错的service只显示app名称不显示IP和端口

**What really happened**:
ip none, app none
![screenshot from 2016-12-09 11-31-35](https://cloud.githubusercontent.com/assets/10137744/21036730/0f1c4f18-be03-11e6-9983-c71061be9e67.png)

**Comment by dorrywhale** [comment]
我会和 @Anna-92 沟通给出设计。

**Comment by BelindaLiu** [comment]
V0.1.14-alpha fixed.
