### ISSUE TITLE
service详情页没有标题和image名

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#78]
**Dorry UI Build Versin:**
Version:  0.2.0-hotfix-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想查看service的详细信息

**Where I am**
service页面

**What I have done**
点击service图标，进入详情页

**What I expect:**
详情页本身的标题，以及imges的名字

**What really happened**:
没有标题和image名

**Comment by Anna-92** [comment]
另，凡是无数据显示的地方，全部是空白，没有文字 ’None' 显示。

**Comment by dorry-terryli** [comment]
会添加subtitle

**Comment by dorrywhale** [comment]
Pass scenario
