### ISSUE TITLE
所有页面的button都没有动态效果

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#80]
**Dorry UI Build Versin:**
Version:  0.2.0-hotfix-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想查看app信息

**Where I am**
app页面

**What I have done**
查看

**What I expect:**
鼠标hover到button应该有动态效果

**What really happened**:
只有点击button才有动态效果

**Comment by Anna-92** [comment]
@BelindaLiu 指哪个button？

**Comment by BelindaLiu** [comment]
V0.1.12-alpha fixed.
