### ISSUE TITLE
market页面缺少文字说明

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#84]
**Dorry UI Build Versin:**
Version:  0.2.0-hotfix-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想查看app信息

**Where I am**
market页面

**What I have done**
进入market页面查看

**What I expect:**
market包含哪方面工具之类的基础介绍
以及不同app的版本号，文件大小，更新日期等信息

**What really happened**:
缺少以上信息

**Comment by Anna-92** [comment]
@dorry-terryli 我会跟你们讨论market里的app详情的业务，并给出相关设计。

**Comment by dorrywhale** [comment]
@Anna-92 请给出设计

**Comment by dorry-terryli** [comment]
除了文件大小，和更新日期暂时不添加
