### ISSUE TITLE
有旋转图标的时候整个页面外框闪烁

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#85]
**Dorry UI Build Versin:**
Version:  0.2.0-hotfix-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
start app

**Where I am**
app页面

**What I have done**
点击start按钮

**What I expect:**
正常启动

**What really happened**:
页面出现灰色大面积抖动的框线

**Comment by dorry-terryli** [comment]
暂不修，初步推断可能是电脑或者是转圈控件本身的问题
