### ISSUE TITLE
菜单栏里的item状态显示

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-web#87]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Mac mini Os X EI Capitan
Version: 10.11.6

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.98 (64-bit)

**What I want to do**
查看菜单栏界面

**Where I am**
service页面

**What I have done**
点击service进入Service界面

**What I expect:**
当显示页面为service页面时，菜单栏里的service区域呈现被点击状态（蓝色）

**What really happened**:
名字仅显示下划线。

**Comment by dorrywhale** [comment]
Scenario 通过
