### ISSUE TITLE
stop service Dorry_*后管理页面无法访问

### ISSUE THREAD

**Issue by BelindaLiu** [MatchboxDorry/dorry-web#88]
**Dorry UI Build Versin:**
Version:  0.2.0-hotfix-alpha

**Operation System:**
Name: Ubuntu
Version: 16.04-LTS(64bit)

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.59 

**What I want to do**
想stop service

**Where I am**
service页面

**What I have done**
点击stopl按钮

**What I expect:**
stop成功

**What really happened**:
管理页面消失，再也无法访问

![screenshot from 2016-12-09 11-11-48](https://cloud.githubusercontent.com/assets/10137744/21037229/189c0638-be07-11e6-9f74-52a314a840b0.png)
![screenshot from 2016-12-09 12-00-51](https://cloud.githubusercontent.com/assets/10137744/21037239/27864dfc-be07-11e6-9eb0-fe1f58e7ebc9.png)

**Comment by dorrywhale** [comment]
点击了哪个service？@Belinda

**Comment by BelindaLiu** [comment]
V0.1.12-alpha fixed.
