### ISSUE TITLE
Error Services无‘删除所有’的按钮

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-web#89]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Mac mini Os X EI Capitan
Version: 10.11.6

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.98 (64-bit)

**What I want to do**
想看到error services里的删除所有按钮

**Where I am**
service页面

**What I have done**
查看error services部分

**What I expect:**
想看到error services里的'删除所有‘的按钮

**What really happened**:
无该按钮显示

**Comment by dorrywhale** [comment]
Scenario 通过
