### ISSUE TITLE
error services里图标旁的出错icon

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-web#90]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Mac mini Os X EI Capitan
Version: 10.11.6

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.98 (64-bit)

**What I want to do**
查看error service上的出错icon

**Where I am**
service页面

**What I have done**
查看了error service模块的界面

**What I expect:**
想看到error service图标旁边的出错Icon

**What really happened**:
无该icon显示

**Comment by BelindaLiu** [comment]
V0.1.12-alpha fixed.

**Comment by dorrywhale** [comment]
@LiuBiHongHong 请说明这个Issue现在的状态

**Comment by LiuBiHongHong** [comment]
出错图标暂时先用一个感叹号表示，以后想到更好的方法再改进。
