### ISSUE TITLE
操作失败提示的界面

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-web#93]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Mac mini Os X EI Capitan
Version: 10.11.6

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.98 (64-bit)

**What I want to do**
想删除一个app看到它的操作失败提示界面

**Where I am**
app页面

**What I have done**
删除了一个app，看到了显示操作失败的提示

**What I expect:**
操作失败的提示框背景是黄色的

**What really happened**:
提示框的背景颜色变成红色

**Comment by Anna-92** [comment]
@dorry-terryli 对于操作失败提示里的图标，我会给出新的设计。另，请把背景色改成黄色

**Comment by dorrywhale** [comment]
@anna, 测试的时候的身份是用户，不要使用“我”这种字样。
