### ISSUE TITLE
每个service或app上的图标

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-web#95]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Mac mini Os X EI Capitan
Version: 10.11.6

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.98 (64-bit)

**What I want to do**
想看到所有services上的图标

**Where I am**
service页面

**What I have done**
看了service页面的所有services的图标

**What I expect:**
想看到每个service上都有图标，而且不同的颜色显示其状态。

**What really happened**:
图标位置用一个默认图标代替，而且还有投影。

**Comment by Anna-92** [comment]
@dorry-terryli 请将默认图标替换，另外，投影不需要。

**Comment by dorry-terryli** [comment]
@Anna-92 需给出默认图标
