### ISSUE TITLE
app里的tooltip位置

### ISSUE THREAD

**Issue by Anna-92** [MatchboxDorry/dorry-web#98]
**Dorry UI Build Versin:**
Version: 0.1.６-alpha

**Operation System:**
Name: Mac mini Os X EI Capitan
Version: 10.11.6

**Browser:**
Browser name: Chrome
Browser version: 54.0.2840.98 (64-bit)

**What I want to do**
想查看app的tooltip

**Where I am**
app界面

**What I have done**
进入app界面，鼠标挪至app的icon上查看弹出的tooltip

**What I expect:**
tooltip的位置在图标的正下方

**What really happened**:
tooltip位置偏左，而且第一个app的tooltip与菜单栏是零距离。

**Comment by dorry-terryli** [comment]
第一个ｔｏｏｌｔｉｐ位置会做调整

**Comment by dorrywhale** [comment]
@LiuBiHongHong 没有在应用详情页面看到 ID号

**Comment by LiuBiHongHong** [comment]
fixed @dorrywhale
